# Jekyll configuration

name: Geozak's Blog
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
url: https://geozak.github.io

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: '/blog'

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: false

social:
  github: geozak
  stackoverflow: 
  linkedin: 'zakary-stone-84925048'
  instagram: 
  lastfm: 
  #rss: feed.xml
  rss:

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: geozakblog
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE', '.htaccess', 'prep-tags-for-git.sh']